# Generated by Django 5.0.7 on 2024-10-14 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_comments_item_comments_message_comments_writer"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="bids",
            name="userbidding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userbid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricebid",
                to="auctions.bids",
            ),
        ),
    ]
