# Generated by Django 5.0.7 on 2024-10-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_bids_bid_bids_userbidding_alter_auctionlisting_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bids",
            name="bid",
            field=models.IntegerField(default=0),
        ),
    ]
