# Generated by Django 5.0.7 on 2024-10-15 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_remove_bids_bid_remove_bids_userbidding_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bids",
            name="bid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bids",
            name="userbidding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userbidding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="imageurl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidprice",
                to="auctions.bids",
            ),
        ),
    ]
