# Generated by Django 5.0.7 on 2024-10-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0008_bids_bid_bids_userbidding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="imageurl",
            field=models.CharField(default="No Image", max_length=1000),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="price",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bidprice",
                to="auctions.bids",
            ),
        ),
    ]
